import { useCallback, useEffect, useMemo, useState, type ReactNode } from 'react'
import { Clipboard, ExternalLink, Filter, Link as LinkIcon, Pencil, Plus, RefreshCw, Search, Server, Settings, Trash2, X } from 'lucide-react'

type ServiceType = 'frontend' | 'backend'
type LinkInfo = { url: string; label: string; source: string; pageTitle?: string; iconUrl?: string; reachability: string; localOnly: boolean; hostPort?: number; containerPort?: number }
type ProbeRecord = { url: string; at: string; status?: string; title?: string; reachability: string; error?: string }
type Service = { serviceKey: string; name: string; pageTitle?: string; iconUrl?: string; serviceType: ServiceType; containerName: string; image: string; composeProject?: string; composeService?: string; containerState: string; running: boolean; paused: boolean; hidden: boolean; group: string; description: string; icon: string; primaryUrl?: string; primaryLink?: LinkInfo; links: LinkInfo[]; publishedPorts: { hostIp: string; hostPort: number; containerPort: number; protocol: string }[]; linkSource?: string; reachability: string; localOnly: boolean; stale: boolean; lastSeenAt: string; probeHistory?: ProbeRecord[]; lastProbeAt?: string; lastProbeStatus?: string; lastError?: string }
type CustomLink = { id: string; tabId: string; url: string; originalUrl?: string; name: string; description: string; icon: string; iconUrl?: string; pageTitle?: string; reachability: string; lastProbeAt?: string; lastProbeStatus?: string; lastError?: string; sortOrder: number }
type CustomTab = { id: string; name: string; sortOrder: number; links: CustomLink[] }
type Settings = { mockIp?: string; mockIps: Record<string, string> }
type Status = { docker: { available: boolean; lastError?: string }; lastReconcileAt?: string; stale: boolean }

const sourceLabels: Record<string, string> = { manual: '手工配置', label: 'Docker 标签', 'published-port': '发布端口' }
const reachLabels: Record<string, string> = { reachable: '可访问', 'responding-authenticated': '需要登录', 'responding-error': '服务已响应', unconfirmed: '待确认', 'not-checked': '不检查（localhost）', 'local-only': '仅 NAS 本机', 'not-published': '未发布端口', invalid: '链接无效' }
const typeLabels: Record<ServiceType, string> = { frontend: '前台服务', backend: '后台服务' }

function normalizeService(service: Service): Service { return { ...service, serviceType: service.serviceType === 'backend' ? 'backend' : 'frontend', links: service.links ?? [], publishedPorts: service.publishedPorts ?? [], probeHistory: service.probeHistory ?? [] } }
function normalizeTab(tab: CustomTab): CustomTab { return { ...tab, links: tab.links ?? [] } }
function normalizeSettings(settings?: Partial<Settings>): Settings { return { mockIps: settings?.mockIps ?? (settings?.mockIp ? { frontend: settings.mockIp } : {}) } }
async function getJSON<T>(url: string): Promise<T> { const response = await fetch(url); if (!response.ok) throw new Error(`${response.status} ${response.statusText}`); return response.json() }
function responsive(link: { reachability: string; localOnly?: boolean }) { return ['reachable', 'responding-authenticated', 'responding-error'].includes(link.reachability) && !link.localOnly }
function openable(link: { reachability: string; localOnly?: boolean }) { return responsive(link) || link.reachability === 'not-checked' }
function faviconURL(rawURL?: string) {
  if (!rawURL) return ''
  try {
    const parsed = new URL(rawURL)
    if (parsed.protocol !== 'http:' && parsed.protocol !== 'https:') return ''
    return `${parsed.origin}/favicon.ico`
  } catch {
    return ''
  }
}
function WebIcon({ url, iconUrl, fallback }: { url?: string; iconUrl?: string; fallback: ReactNode }) {
  const fallbackURL = faviconURL(url)
  const [src, setSrc] = useState(iconUrl || fallbackURL)
  useEffect(() => setSrc(iconUrl || fallbackURL), [iconUrl, fallbackURL])
  if (!src) return fallback
  return <img className="web-icon" src={src} alt="" loading="lazy" onError={() => setSrc(src === iconUrl ? fallbackURL : '')} />
}
function encoded(value: string) { return encodeURIComponent(value) }

export default function App() {
  const [services, setServices] = useState<Service[]>([])
  const [customTabs, setCustomTabs] = useState<CustomTab[]>([])
  const [settings, setSettings] = useState<Settings>({ mockIps: {} })
  const [status, setStatus] = useState<Status | null>(null)
  const [query, setQuery] = useState('')
  const [group, setGroup] = useState('')
  const [state, setState] = useState('all')
  const [includeHidden, setIncludeHidden] = useState(false)
  const [activeTab, setActiveTab] = useState('frontend')
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState('')
  const [selectedService, setSelectedService] = useState<Service | null>(null)
  const [editingLink, setEditingLink] = useState<CustomLink | null>(null)
  const [linkEditorTabId, setLinkEditorTabId] = useState('')
  const [showLinkEditor, setShowLinkEditor] = useState(false)
  const [showSettings, setShowSettings] = useState(false)
  const [showTabManager, setShowTabManager] = useState(false)
  const [newTabName, setNewTabName] = useState('')
  const [tabDraft, setTabDraft] = useState('')
  const [message, setMessage] = useState('')

  const load = useCallback(async (manual = false) => {
    if (manual) setLoading(true)
    try {
      const params = new URLSearchParams({ q: query, group, state, include_hidden: String(includeHidden) })
      const [list, currentStatus, navigation] = await Promise.all([
        getJSON<{ services: Service[] }>(`/api/v1/services?${params}`),
        getJSON<Status>('/api/v1/status'),
        getJSON<{ settings: Settings; customTabs: CustomTab[] }>('/api/v1/navigation'),
      ])
      setServices(list.services.map(normalizeService)); setStatus(currentStatus); setSettings(normalizeSettings(navigation.settings)); setCustomTabs((navigation.customTabs ?? []).map(normalizeTab)); setError('')
    } catch (e) { setError(e instanceof Error ? e.message : '加载失败') } finally { setLoading(false) }
  }, [query, group, state, includeHidden])

  useEffect(() => { void load(true); const timer = window.setInterval(() => void load(), 10000); return () => window.clearInterval(timer) }, [load])

  const groups = useMemo(() => Array.from(new Set(services.map(s => s.group).filter(Boolean))).sort(), [services])
  const currentCustomTab = customTabs.find(tab => tab.id === activeTab)
  const activeTabName = activeTab === 'frontend' ? '前台服务' : activeTab === 'backend' ? '后台服务' : currentCustomTab?.name ?? '当前 Tab'
  const activeMockIp = settings.mockIps[activeTab] ?? ''
  const isCustomTab = Boolean(currentCustomTab)
  const frontendCount = services.filter(s => s.serviceType === 'frontend').length
  const backendCount = services.filter(s => s.serviceType === 'backend').length
  const visibleServices = useMemo(() => isCustomTab ? [] : services.filter(s => s.serviceType === activeTab), [services, activeTab, isCustomTab])
  const visibleLinks = useMemo(() => {
    if (!currentCustomTab) return []
    const term = query.trim().toLowerCase()
    return currentCustomTab.links.filter(link => !term || `${link.name} ${link.pageTitle ?? ''} ${link.url} ${link.description}`.toLowerCase().includes(term))
  }, [currentCustomTab, query])
  const activeCount = isCustomTab ? visibleLinks.length : visibleServices.length
  const runningCount = visibleServices.filter(s => s.running).length
  const reachableCount = isCustomTab ? visibleLinks.filter(link => responsive(link)).length : visibleServices.filter(s => responsive({ reachability: s.reachability, localOnly: s.localOnly })).length
  const pendingCount = isCustomTab ? visibleLinks.filter(link => link.reachability === 'unconfirmed').length : visibleServices.filter(s => s.reachability === 'unconfirmed').length
  const errorCount = isCustomTab ? visibleLinks.filter(link => link.lastError || link.reachability === 'invalid').length : visibleServices.filter(s => s.lastError || s.reachability === 'invalid').length

  const refresh = async () => { setLoading(true); try { const response = await fetch('/api/v1/reconcile', { method: 'POST' }); if (!response.ok) throw new Error('刷新失败'); await load() } catch (e) { setError(e instanceof Error ? e.message : '刷新失败') } finally { setLoading(false) } }
  const reprobe = async () => { if (!selectedService) return; const response = await fetch(`/api/v1/services/${encoded(selectedService.serviceKey)}/probe`, { method: 'POST' }); if (!response.ok) { window.alert('重新探测失败'); return }; const updated = normalizeService(await response.json() as Service); setSelectedService(updated); setServices(current => current.map(item => item.serviceKey === updated.serviceKey ? updated : item)) }
  const copy = async (url: string) => { try { await navigator.clipboard.writeText(url); setMessage('链接已复制') } catch { window.prompt('复制链接', url) } }
  const createTab = async () => { const name = newTabName.trim(); if (!name) { setMessage('请输入 Tab 名称'); return }; const response = await fetch('/api/v1/custom-tabs', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ name }) }); if (!response.ok) { setMessage('创建 Tab 失败'); return }; const tab = normalizeTab(await response.json() as CustomTab); setNewTabName(''); setCustomTabs(current => [...current, tab]); setActiveTab(tab.id); setShowTabManager(true); setMessage('Tab 已创建') }
  const renameTab = async () => { if (!currentCustomTab) return; const name = tabDraft.trim(); if (!name) { setMessage('请输入 Tab 名称'); return }; const response = await fetch(`/api/v1/custom-tabs/${encoded(currentCustomTab.id)}`, { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ name, sortOrder: currentCustomTab.sortOrder }) }); if (!response.ok) { setMessage('Tab 重命名失败'); return }; const updated = normalizeTab(await response.json() as CustomTab); setCustomTabs(current => current.map(tab => tab.id === updated.id ? updated : tab)); setMessage('Tab 名称已保存') }
  const deleteTab = async () => { if (!currentCustomTab || !window.confirm(`删除 Tab「${currentCustomTab.name}」及其链接？`)) return; const response = await fetch(`/api/v1/custom-tabs/${encoded(currentCustomTab.id)}`, { method: 'DELETE' }); if (!response.ok) { setMessage('删除 Tab 失败'); return }; setCustomTabs(current => current.filter(tab => tab.id !== currentCustomTab.id)); setActiveTab('frontend'); setMessage('Tab 已删除') }
  const saveSettings = async (tabId: string, mockIp: string) => { const response = await fetch('/api/v1/settings', { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ tabId, mockIp: mockIp.trim() }) }); if (!response.ok) { const body = await response.json().catch(() => ({})); setMessage(body.error || '设置保存失败'); return }; setSettings(normalizeSettings(await response.json() as Settings)); setShowSettings(false); await load(); setMessage(`${activeTabName} 的跳转 IP 已保存`) }
  const deleteLink = async (link: CustomLink) => { if (!window.confirm(`删除链接「${link.name || link.url}」？`)) return; const response = await fetch(`/api/v1/custom-links/${encoded(link.id)}`, { method: 'DELETE' }); if (!response.ok) { setMessage('删除链接失败'); return }; await load(); setMessage('链接已删除') }
  const probeLink = async (link: CustomLink) => { const response = await fetch(`/api/v1/custom-links/${encoded(link.id)}/probe`, { method: 'POST' }); if (!response.ok) { setMessage('链接探测失败'); return }; await load(); setMessage('链接已重新探测') }

  useEffect(() => { if (currentCustomTab) setTabDraft(currentCustomTab.name) }, [currentCustomTab?.id, currentCustomTab?.name])

  return <main className="shell">
    <header className="topbar"><div className="brand"><div className="brand-mark"><Server size={24} /></div><div><h1>NAS Home</h1><p>发现本机容器服务，也维护你关心的外部链接。</p></div></div><div className="sync"><span className={status?.docker.available ? 'dot online' : 'dot'} /> Docker {status?.docker.available ? '已连接' : '不可用'}<small>{status?.lastReconcileAt ? `最后同步 ${new Date(status.lastReconcileAt).toLocaleTimeString()}` : '尚未同步'}</small><button className="ghost" onClick={() => setShowSettings(value => !value)}><Settings size={16} />设置</button><button className="ghost" onClick={() => void refresh()}><RefreshCw size={16} />刷新</button></div></header>
    {status?.stale || error ? <div className="alert"><strong>{error ? '数据读取异常' : '数据可能已过期'}</strong><span>{error || status?.docker.lastError || '保留上一次快照，等待 Docker 恢复。'}</span></div> : null}
    {showSettings ? <SettingsPanel tabId={activeTab} tabName={activeTabName} mockIp={activeMockIp} onSave={saveSettings} /> : null}
    <nav className="service-tabs" aria-label="服务分类"><button className={activeTab === 'frontend' ? 'active' : ''} onClick={() => setActiveTab('frontend')}>前台服务 <b>{frontendCount}</b></button><button className={activeTab === 'backend' ? 'active' : ''} onClick={() => setActiveTab('backend')}>后台服务 <b>{backendCount}</b></button>{customTabs.map(tab => <button key={tab.id} className={activeTab === tab.id ? 'active custom' : 'custom'} onClick={() => setActiveTab(tab.id)}>{tab.name} <b>{tab.links.length}</b></button>)}<button className="tab-add" onClick={() => setShowTabManager(value => !value)}><Plus size={15} />自定义 Tab</button></nav>
    {showTabManager ? <TabManager newTabName={newTabName} setNewTabName={setNewTabName} onCreate={() => void createTab()} currentTab={currentCustomTab} draft={tabDraft} setDraft={setTabDraft} onRename={() => void renameTab()} onDelete={() => void deleteTab()} /> : null}
    <section className="stats"><Stat label={isCustomTab ? '当前链接' : '运行中容器'} value={isCustomTab ? activeCount : runningCount} tone="blue" /><Stat label="可访问服务" value={reachableCount} tone="green" /><Stat label={isCustomTab ? '待确认链接' : '待确认端口'} value={pendingCount} tone="amber" /><Stat label="异常" value={errorCount} tone="red" /></section>
    <section className="toolbar"><label className="search"><Search size={18} /><input value={query} onChange={e => setQuery(e.target.value)} placeholder={isCustomTab ? '搜索链接名称、URL或描述' : '搜索名称、容器、镜像或 Compose service'} /></label>{!isCustomTab && <><label className="select"><Filter size={16} /><select value={group} onChange={e => setGroup(e.target.value)}><option value="">全部分组</option>{groups.map(g => <option key={g}>{g}</option>)}</select></label><label className="select"><select value={state} onChange={e => setState(e.target.value)}><option value="all">全部状态</option><option value="running">运行中</option><option value="stopped">已停止</option></select></label><label className="toggle"><input type="checkbox" checked={includeHidden} onChange={e => setIncludeHidden(e.target.checked)} />显示已隐藏</label></>}{isCustomTab && <button className="primary small" onClick={() => { setLinkEditorTabId(currentCustomTab?.id ?? ''); setEditingLink(null); setShowLinkEditor(true) }}><Plus size={15} />添加链接</button>}</section>
    {message ? <div className="toast">{message}</div> : null}
    {loading && services.length === 0 && customTabs.length === 0 ? <div className="state-box">正在读取本机容器…</div> : error && services.length === 0 ? <div className="state-box"><Server size={40} /><h2>暂时无法连接 Docker</h2><p>服务会保留已有快照；请检查 Docker socket 或代理。</p></div> : isCustomTab ? (visibleLinks.length ? <section className="service-grid">{visibleLinks.map(link => <CustomLinkCard key={link.id} link={link} onOpen={() => window.open(link.url, '_blank', 'noopener,noreferrer')} onCopy={copy} onEdit={() => { setEditingLink(link); setLinkEditorTabId(link.tabId); setShowLinkEditor(true) }} onDelete={() => void deleteLink(link)} onProbe={() => void probeLink(link)} />)}</section> : <div className="state-box"><LinkIcon size={40} /><h2>这个 Tab 还没有链接</h2><p>添加一个 URL 即可自动探测页面标题和可达性。</p></div>) : visibleServices.length === 0 ? <div className="state-box"><Server size={40} /><h2>没有匹配的{typeLabels[activeTab as ServiceType]}</h2><p>调整搜索或筛选条件后再试。</p></div> : <section className="service-grid">{visibleServices.map(service => <ServiceCard key={service.serviceKey} service={service} onDetail={() => setSelectedService(service)} onCopy={copy} />)}</section>}
    {selectedService ? <aside className="drawer"><div className="drawer-head"><div><span className="eyebrow">服务详情 · {typeLabels[selectedService.serviceType]}</span><h2>{selectedService.pageTitle || selectedService.name}</h2></div><button className="icon-button" onClick={() => setSelectedService(null)}><X /></button></div><dl className="details"><dt>页面标题</dt><dd>{selectedService.pageTitle || '未探测到页面 title'}</dd><dt>稳定 Key</dt><dd>{selectedService.serviceKey}</dd><dt>所属容器</dt><dd>{selectedService.containerName}</dd><dt>镜像</dt><dd className="wrap">{selectedService.image}</dd><dt>状态</dt><dd>{selectedService.containerState}</dd><dt>分组</dt><dd>{selectedService.group || '未分组'}</dd><dt>服务类型</dt><dd>{typeLabels[selectedService.serviceType]}</dd><dt>入口</dt><dd>{selectedService.primaryUrl || reachLabels[selectedService.reachability] || '无'}</dd></dl><h3>Published ports</h3><div className="port-list">{selectedService.publishedPorts.length ? selectedService.publishedPorts.map((p, i) => <div key={`${p.hostPort}-${i}`}><code>{p.hostIp || '0.0.0.0'}:{p.hostPort}</code><span>→ 容器 {p.containerPort}/{p.protocol}</span></div>) : <p>没有已发布端口，默认归类为后台服务</p>}</div><h3>链接来源</h3><p className="muted">{sourceLabels[selectedService.linkSource || ''] || '未生成自动链接'} · {reachLabels[selectedService.reachability] || selectedService.reachability}</p><button className="probe-button" onClick={() => void reprobe()}><RefreshCw size={14} />重新探测</button><h3>最近探测</h3><div className="probe-history">{selectedService.probeHistory?.length ? selectedService.probeHistory.slice().reverse().map((probe, index) => <div key={`${probe.at}-${index}`}><span>{new Date(probe.at).toLocaleString()}</span><strong>{probe.title || reachLabels[probe.reachability] || probe.reachability}</strong><small>{probe.status || probe.error || '无状态'}</small></div>) : <p>暂无探测记录</p>}</div><OverrideEditor key={selectedService.serviceKey} service={selectedService} onSaved={updated => { const next = normalizeService(updated); setSelectedService(next); setServices(current => current.map(item => item.serviceKey === next.serviceKey ? next : item)) }} /></aside> : null}
    {showLinkEditor ? <CustomLinkEditor link={editingLink} tabId={linkEditorTabId} onClose={() => setShowLinkEditor(false)} onSaved={async () => { setShowLinkEditor(false); await load(); setMessage(editingLink ? '链接已保存' : '链接已添加') }} /> : null}
  </main>
}

function Stat({ label, value, tone }: { label: string; value: number; tone: string }) { return <div className={`stat ${tone}`}><span>{label}</span><strong>{value}</strong></div> }
function SettingsPanel({ tabId, tabName, mockIp, onSave }: { tabId: string; tabName: string; mockIp: string; onSave: (tabId: string, value: string) => Promise<void> }) { const [value, setValue] = useState(mockIp); useEffect(() => setValue(mockIp), [tabId, mockIp]); return <section className="management-panel settings-panel"><div><strong>{tabName} · 跳转 IP</strong><p>只作用于当前 Tab。填写 localhost 时替换链接但跳过服务可达性探测；留空恢复原始域名。</p></div><div className="inline-form"><input value={value} onChange={e => setValue(e.target.value)} placeholder="例如 192.168.1.11 或 localhost" /><button className="primary" onClick={() => void onSave(tabId, value)}>保存</button></div></section> }
function TabManager({ newTabName, setNewTabName, onCreate, currentTab, draft, setDraft, onRename, onDelete }: { newTabName: string; setNewTabName: (value: string) => void; onCreate: () => void; currentTab?: CustomTab; draft: string; setDraft: (value: string) => void; onRename: () => void; onDelete: () => void }) { return <section className="management-panel tab-manager"><div><strong>新增自定义 Tab</strong><div className="inline-form"><input value={newTabName} onChange={e => setNewTabName(e.target.value)} placeholder="例如 常用外部服务" /><button className="primary" onClick={onCreate}><Plus size={15} />创建</button></div></div>{currentTab ? <div><strong>维护当前 Tab</strong><div className="inline-form"><input value={draft} onChange={e => setDraft(e.target.value)} /><button className="secondary" onClick={onRename}><Pencil size={14} />重命名</button><button className="danger" onClick={onDelete}><Trash2 size={14} />删除</button></div></div> : <p className="muted">切换到自定义 Tab 后可重命名或删除。</p>}</section> }
function CustomLinkCard({ link, onOpen, onCopy, onEdit, onDelete, onProbe }: { link: CustomLink; onOpen: () => void; onCopy: (url: string) => void; onEdit: () => void; onDelete: () => void; onProbe: () => void }) { const title = link.name || link.pageTitle || link.url; return <article className="card custom-link-card"><div className="card-head"><div className="service-icon"><WebIcon url={link.originalUrl || link.url} iconUrl={link.iconUrl} fallback={<LinkIcon size={30} />} /></div><div className="card-title"><h2 title={title}>{title}</h2><span className="container-name" title={link.url}>链接：{link.url}</span></div></div>{link.description && <p className="description">{link.description}</p>}<div className="link-row"><code title={link.url}>{link.url}</code><div className="actions"><button onClick={onOpen}><ExternalLink size={15} />打开</button><button className="secondary" onClick={() => onCopy(link.url)}><Clipboard size={15} />复制</button></div></div><div className="card-actions"><button className="detail-link" onClick={onProbe}><RefreshCw size={13} />重新探测</button><button className="detail-link" onClick={onEdit}><Pencil size={13} />编辑</button><button className="detail-link danger-text" onClick={onDelete}><Trash2 size={13} />删除</button></div></article> }
function CustomLinkEditor({ link, tabId, onClose, onSaved }: { link: CustomLink | null; tabId: string; onClose: () => void; onSaved: () => Promise<void> }) { const [url, setUrl] = useState(link?.originalUrl ?? link?.url ?? ''); const [name, setName] = useState(link?.name ?? ''); const [description, setDescription] = useState(link?.description ?? ''); const [icon, setIcon] = useState(link?.icon ?? ''); const [sortOrder, setSortOrder] = useState(link?.sortOrder ?? 0); const [message, setMessage] = useState(''); const save = async () => { if (!url.trim()) { setMessage('URL 不能为空'); return }; setMessage('探测并保存中…'); const payload = { tabId, url: url.trim(), name: name.trim(), description: description.trim(), icon: icon.trim(), sortOrder }; const endpoint = link ? `/api/v1/custom-links/${encoded(link.id)}` : `/api/v1/custom-tabs/${encoded(tabId)}/links`; const response = await fetch(endpoint, { method: link ? 'PATCH' : 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(payload) }); if (!response.ok) { const body = await response.json().catch(() => ({})); setMessage(body.error || '保存失败'); return }; await onSaved() }; return <aside className="drawer link-editor"><div className="drawer-head"><div><span className="eyebrow">{link ? '编辑自定义链接' : '添加自定义链接'}</span><h2>{link ? link.name || link.url : '新链接'}</h2></div><button className="icon-button" onClick={onClose}><X /></button></div><p className="muted">只填 URL 也可以，保存时会自动探测页面标题、HTTP 状态和可达性。</p><div className="override-grid"><label className="wide">URL（必填）<input value={url} onChange={e => setUrl(e.target.value)} placeholder="https://example.com" /></label><label>名称<input value={name} onChange={e => setName(e.target.value)} placeholder="留空使用页面 title" /></label><label>图标<input value={icon} onChange={e => setIcon(e.target.value)} placeholder="可选 emoji" /></label><label className="wide">描述<input value={description} onChange={e => setDescription(e.target.value)} placeholder="可选说明" /></label><label>排序<input type="number" value={sortOrder} onChange={e => setSortOrder(Number(e.target.value))} /></label></div><div className="override-actions"><button onClick={() => void save()}>保存并探测</button><button className="secondary" onClick={onClose}>取消</button><span>{message}</span></div></aside> }
function ServiceCard({ service, onDetail, onCopy }: { service: Service; onDetail: () => void; onCopy: (url: string) => void }) { const title = service.pageTitle || service.name || service.containerName; const links = service.links.filter(link => link.url && (link.source === 'manual' || openable(link))).sort((a, b) => (a.hostPort || 0) - (b.hostPort || 0)); const primaryLink = service.primaryLink || links[0]; return <article className={`card ${!service.running ? 'stopped' : ''}`}><div className="card-head"><div className="service-icon"><WebIcon url={service.primaryUrl || primaryLink?.url} iconUrl={service.iconUrl || primaryLink?.iconUrl} fallback={<Server size={30} />} /></div><div className="card-title"><h2 title={title}>{title}</h2><span className="container-name" title={service.containerName}>容器：{service.containerName}</span></div><span className={`status ${service.running ? 'running' : 'stopped'}`}>{service.containerState}</span></div>{service.description && <p className="description">{service.description}</p>}<div className="link-list">{links.length ? links.map((link, index) => <div className="link-row" key={`${link.url}-${link.hostPort || index}`}><code title={link.url}>{link.hostPort ? `${link.hostPort} · ` : ''}{link.url}</code><div className="actions"><button onClick={() => window.open(link.url, '_blank', 'noopener,noreferrer')}><ExternalLink size={15} />打开</button><button className="secondary" onClick={() => onCopy(link.url)}><Clipboard size={15} />复制</button></div></div>) : <div className="link-row"><span className="no-link">{reachLabels[service.reachability] || '没有已确认入口'}</span><div className="actions"><button onClick={onDetail}>详情</button></div></div>}</div>{service.publishedPorts.length > 0 && <div className="ports">{service.publishedPorts.slice().sort((a, b) => a.hostPort - b.hostPort).map(p => <span key={`${p.hostPort}/${p.protocol}`}>{p.hostIp || '0.0.0.0'}:{p.hostPort} → {p.containerPort}/{p.protocol}</span>)}</div>}<button className="detail-link" onClick={onDetail}>查看详情</button></article> }
function OverrideEditor({ service, onSaved }: { service: Service; onSaved: (service: Service) => void }) { const [name, setName] = useState(service.name); const [group, setGroup] = useState(service.group); const [description, setDescription] = useState(service.description); const [url, setUrl] = useState(service.primaryUrl || ''); const [hidden, setHidden] = useState(service.hidden); const [serviceType, setServiceType] = useState<ServiceType>(service.serviceType); const [sortOrder, setSortOrder] = useState(0); const [message, setMessage] = useState(''); const endpoint = `/api/v1/services/${encoded(service.serviceKey)}/override`; const save = async () => { setMessage('保存中…'); const payload: Record<string, unknown> = { name, group, description, hidden, sortOrder, serviceType }; if (url.trim()) payload.url = url.trim(); try { const response = await fetch(endpoint, { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(payload) }); if (!response.ok) { const body = await response.json().catch(() => ({})); setMessage(body.error || '保存失败'); return }; onSaved(await response.json() as Service); setMessage('已保存') } catch { setMessage('保存失败，请检查网络') } }; const remove = async () => { setMessage('恢复中…'); try { const response = await fetch(endpoint, { method: 'DELETE' }); if (!response.ok) { setMessage('恢复失败'); return }; onSaved(await response.json() as Service); setMessage('已恢复 Docker 配置') } catch { setMessage('恢复失败，请检查网络') } }; return <section className="override"><h3>手工配置</h3><div className="override-grid"><label>名称<input value={name} onChange={e => setName(e.target.value)} /></label><label>分组<input value={group} onChange={e => setGroup(e.target.value)} /></label><label>服务类型<select value={serviceType} onChange={e => setServiceType(e.target.value as ServiceType)}><option value="frontend">前台服务</option><option value="backend">后台服务</option></select></label><label>排序<input type="number" value={sortOrder} onChange={e => setSortOrder(Number(e.target.value))} /></label><label className="wide">描述<input value={description} onChange={e => setDescription(e.target.value)} /></label><label className="wide">URL<input value={url} onChange={e => setUrl(e.target.value)} placeholder="http(s)://host:port/path" /></label></div><div className="override-actions"><button onClick={() => void save()}>保存配置</button><button className="secondary" onClick={() => void remove()}>恢复自动发现</button><span>{message}</span></div></section> }
